export type Item = {
  id: number;
  name: string;
  description: string;
  suggestedPrice: number;
  actualPrice: number;
  imageUrl: string;
};

export const items: Item[] = [
  {
    id: 1,
    name: "Had Soppett",
    description: "Nescafe - Frothy French Vanilla",
    suggestedPrice: 7.87,
    actualPrice: 5.54,
    imageUrl: "http://dummyimage.com/184x100.png/dddddd/000000",
  },
  {
    id: 2,
    name: "Caril Kerswill",
    description: "Ginger - Ground",
    suggestedPrice: 8.35,
    actualPrice: 1.86,
    imageUrl: "http://dummyimage.com/233x100.png/dddddd/000000",
  },
  {
    id: 3,
    name: "Dorise Curteis",
    description: "Cheese - Valancey",
    suggestedPrice: 1.59,
    actualPrice: 9.56,
    imageUrl: "http://dummyimage.com/173x100.png/dddddd/000000",
  },
  {
    id: 4,
    name: "Lizzy Rabjohns",
    description: "Avocado",
    suggestedPrice: 5.33,
    actualPrice: 9.15,
    imageUrl: "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
  },
  {
    id: 5,
    name: "Nero Gellert",
    description: "Food Colouring - Green",
    suggestedPrice: 2.79,
    actualPrice: 8.14,
    imageUrl: "http://dummyimage.com/100x100.png/ff4444/ffffff",
  },
  {
    id: 6,
    name: "Adoree Sadd",
    description: "Radish",
    suggestedPrice: 8.72,
    actualPrice: 6.14,
    imageUrl: "http://dummyimage.com/162x100.png/ff4444/ffffff",
  },
  {
    id: 7,
    name: "Hi Broscombe",
    description: "Vodka - Hot, Lnferno",
    suggestedPrice: 9.84,
    actualPrice: 8.32,
    imageUrl: "http://dummyimage.com/246x100.png/5fa2dd/ffffff",
  },
  {
    id: 8,
    name: "Myrlene MacAnelley",
    description: "Broccoli - Fresh",
    suggestedPrice: 9.95,
    actualPrice: 3.36,
    imageUrl: "http://dummyimage.com/172x100.png/dddddd/000000",
  },
  {
    id: 9,
    name: "Quentin Orsman",
    description: "Cookie Trail Mix",
    suggestedPrice: 1.97,
    actualPrice: 8.79,
    imageUrl: "http://dummyimage.com/232x100.png/cc0000/ffffff",
  },
  {
    id: 10,
    name: "Granville Partlett",
    description: "Salad Dressing",
    suggestedPrice: 3.77,
    actualPrice: 2.22,
    imageUrl: "http://dummyimage.com/110x100.png/ff4444/ffffff",
  },
  {
    id: 11,
    name: "Meagan Maylott",
    description: "Corn Syrup",
    suggestedPrice: 8.81,
    actualPrice: 4.57,
    imageUrl: "http://dummyimage.com/226x100.png/cc0000/ffffff",
  },
  {
    id: 12,
    name: "Nappie Goodship",
    description: "Lobster - Live",
    suggestedPrice: 0.64,
    actualPrice: 4.83,
    imageUrl: "http://dummyimage.com/126x100.png/5fa2dd/ffffff",
  },
  {
    id: 13,
    name: "Tresa Heinle",
    description: "Sobe - Berry Energy",
    suggestedPrice: 0.7,
    actualPrice: 6.79,
    imageUrl: "http://dummyimage.com/123x100.png/dddddd/000000",
  },
  {
    id: 14,
    name: "Sherlock Wooffitt",
    description: "Juice - Propel Sport",
    suggestedPrice: 8.57,
    actualPrice: 1.82,
    imageUrl: "http://dummyimage.com/113x100.png/ff4444/ffffff",
  },
  {
    id: 15,
    name: "Barnaby Macura",
    description: "Sprouts - Bean",
    suggestedPrice: 5.41,
    actualPrice: 9.54,
    imageUrl: "http://dummyimage.com/117x100.png/dddddd/000000",
  },
  {
    id: 16,
    name: "Cherilynn Crickmoor",
    description: "Swiss Chard - Red",
    suggestedPrice: 5.53,
    actualPrice: 3.73,
    imageUrl: "http://dummyimage.com/226x100.png/cc0000/ffffff",
  },
  {
    id: 17,
    name: "Husain Burburough",
    description: "Pails With Lids",
    suggestedPrice: 4.68,
    actualPrice: 7.93,
    imageUrl: "http://dummyimage.com/148x100.png/dddddd/000000",
  },
  {
    id: 18,
    name: "Edithe Blanko",
    description: "Juice - Orange, 341 Ml",
    suggestedPrice: 9.41,
    actualPrice: 3.72,
    imageUrl: "http://dummyimage.com/202x100.png/5fa2dd/ffffff",
  },
  {
    id: 19,
    name: "Gael Adran",
    description: "Shrimp - Tiger 21/25",
    suggestedPrice: 7.52,
    actualPrice: 1.7,
    imageUrl: "http://dummyimage.com/159x100.png/dddddd/000000",
  },
  {
    id: 20,
    name: "George Flanner",
    description: "Juice - Pineapple, 341 Ml",
    suggestedPrice: 3.64,
    actualPrice: 5.2,
    imageUrl: "http://dummyimage.com/142x100.png/cc0000/ffffff",
  },
];
